"""initial_schema

Revision ID: 58669a9e257d
Revises: 
Create Date: 2026-03-08 18:47:04.206071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58669a9e257d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('isbn13', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('item_type', sa.String(length=50), server_default='book', nullable=False),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=True),
    sa.Column('is_staff_pick', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('staff_pick_note', sa.Text(), nullable=True),
    sa.Column('replacement_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), server_default='0.00', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn'),
    sa.UniqueConstraint('isbn13')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('max_loans', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_copies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), server_default='good', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_reviews_user_book')
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_copy_id', sa.UUID(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waived_by', sa.UUID(), nullable=True),
    sa.Column('waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # === Custom indexes ===
    op.create_index('idx_users_clerk_id', 'users', ['clerk_id'])
    op.create_index('idx_users_email', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'])

    op.create_index('idx_books_search', 'books', ['search_vector'], postgresql_using='gin')
    op.create_index('idx_books_genre', 'books', ['genre'])
    op.create_index('idx_books_item_type', 'books', ['item_type'])
    op.create_index('idx_books_author', 'books', ['author'])
    op.create_index('idx_books_publication_year', 'books', ['publication_year'])
    op.create_index('idx_books_avg_rating', 'books', [sa.text('avg_rating DESC')])
    op.create_index('idx_books_staff_pick', 'books', ['is_staff_pick'], postgresql_where=sa.text('is_staff_pick = true'))

    op.create_index('idx_book_copies_book_id', 'book_copies', ['book_id'])
    op.create_index('idx_book_copies_status', 'book_copies', ['status'])
    op.create_index('idx_book_copies_book_status', 'book_copies', ['book_id', 'status'])

    op.create_index('idx_loans_user_id', 'loans', ['user_id'])
    op.create_index('idx_loans_book_copy_id', 'loans', ['book_copy_id'])
    op.create_index('idx_loans_status', 'loans', ['status'])
    op.create_index('idx_loans_user_status', 'loans', ['user_id', 'status'])
    op.create_index('idx_loans_due_date', 'loans', ['due_date'], postgresql_where=sa.text("status = 'active'"))

    op.create_index('idx_reservations_user_id', 'reservations', ['user_id'])
    op.create_index('idx_reservations_book_id', 'reservations', ['book_id'])
    op.create_index('idx_reservations_status', 'reservations', ['status'])
    op.create_index('idx_reservations_book_pending', 'reservations', ['book_id', 'queue_position'], postgresql_where=sa.text("status = 'pending'"))

    op.create_index('idx_fines_user_id', 'fines', ['user_id'])
    op.create_index('idx_fines_loan_id', 'fines', ['loan_id'])
    op.create_index('idx_fines_status', 'fines', ['status'])
    op.create_index('idx_fines_user_pending', 'fines', ['user_id'], postgresql_where=sa.text("status = 'pending'"))

    op.create_index('idx_reviews_book_id', 'reviews', ['book_id'])
    op.create_index('idx_reviews_user_id', 'reviews', ['user_id'])
    op.create_index('idx_reviews_book_rating', 'reviews', ['book_id', 'rating'])

    op.create_index('idx_api_keys_user_id', 'api_keys', ['user_id'])
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'])
    op.create_index('idx_api_keys_prefix', 'api_keys', ['key_prefix'])

    # === SQL Functions and Triggers ===

    # Full-text search trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION books_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.author, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.description, '')), 'C') ||
                setweight(to_tsvector('english', coalesce(NEW.genre, '')), 'D') ||
                setweight(to_tsvector('english', coalesce(array_to_string(NEW.genres, ' '), '')), 'D');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_books_search_vector
            BEFORE INSERT OR UPDATE OF title, author, description, genre, genres
            ON books
            FOR EACH ROW
            EXECUTE FUNCTION books_search_vector_update();
    """)

    # Update book average rating trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION update_book_rating() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                UPDATE books SET
                    avg_rating = COALESCE((SELECT AVG(rating)::DECIMAL(3,2) FROM reviews WHERE book_id = OLD.book_id), 0),
                    rating_count = (SELECT COUNT(*) FROM reviews WHERE book_id = OLD.book_id),
                    updated_at = now()
                WHERE id = OLD.book_id;
                RETURN OLD;
            ELSE
                UPDATE books SET
                    avg_rating = COALESCE((SELECT AVG(rating)::DECIMAL(3,2) FROM reviews WHERE book_id = NEW.book_id), 0),
                    rating_count = (SELECT COUNT(*) FROM reviews WHERE book_id = NEW.book_id),
                    updated_at = now()
                WHERE id = NEW.book_id;
                RETURN NEW;
            END IF;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_update_book_rating
            AFTER INSERT OR UPDATE OR DELETE ON reviews
            FOR EACH ROW
            EXECUTE FUNCTION update_book_rating();
    """)

    # Updated_at auto-update trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();")
    op.execute("CREATE TRIGGER trg_books_updated_at BEFORE UPDATE ON books FOR EACH ROW EXECUTE FUNCTION update_updated_at();")
    op.execute("CREATE TRIGGER trg_reviews_updated_at BEFORE UPDATE ON reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at();")

    # Calculate fine function
    op.execute("""
        CREATE OR REPLACE FUNCTION calculate_fine(
            p_due_date TIMESTAMPTZ,
            p_return_date TIMESTAMPTZ,
            p_item_type VARCHAR
        ) RETURNS DECIMAL AS $$
        DECLARE
            days_overdue INT;
            daily_rate DECIMAL;
            max_fine DECIMAL := 25.00;
            fine_amount DECIMAL;
        BEGIN
            days_overdue := GREATEST(0, EXTRACT(DAY FROM (p_return_date - p_due_date))::INT);
            IF days_overdue = 0 THEN
                RETURN 0;
            END IF;
            daily_rate := CASE p_item_type
                WHEN 'book' THEN 0.25
                WHEN 'ebook' THEN 0.25
                WHEN 'dvd' THEN 1.00
                WHEN 'audiobook' THEN 0.50
                WHEN 'magazine' THEN 0.10
                ELSE 0.25
            END;
            fine_amount := days_overdue * daily_rate;
            RETURN LEAST(fine_amount, max_fine);
        END;
        $$ LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fines')
    op.drop_table('loans')
    op.drop_table('reviews')
    op.drop_table('reservations')
    op.drop_table('book_copies')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
